### ISSUE TITLE
Create presentation for Pre DEMO

### ISSUE THREAD

**Issue by roman-golubov** [roman-golubov/vue-internship#75]
Template will be provide in next few days.

UPD:
Template
https://docs.google.com/presentation/d/1XvnTrZ9U15_oz7xAM054aiHMwZPsZTew/edit#slide=id.p1

**Comment by Yuliia-Sydorovych** [comment]
https://docs.google.com/presentation/d/13HOEj-ExDiX5qGCaIwzDmPyBBfHAQFt-/edit?usp=sharing&ouid=113141542420574126194&rtpof=true&sd=true
